version: '3.9'

services:
  app:
    build: .
    container_name: gestion-colis-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://gestion-colis:123456@mongo:27017/colisdb?authSource=admin
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: gestion-colis-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: colisdb
      MONGO_INITDB_ROOT_USERNAME: gestion-colis
      MONGO_INITDB_ROOT_PASSWORD: 123456

volumes:
  mongo-data:
