spring:
  application:
    name: logistique

  profiles:
    active: prod


security:
  jwt:
    secret-key: "ThisIsAVeryLongAndSecureSecretKeyForJWTAuthThatNeedsToBeAtLeast32Characters1234"
    expiration: 3600000
